// Shared movie data for both movies list and details pages

export const MOVIES = [
    {
        id: 1,
        title: "Interstellar",
        year: 2014,
        rating: 8.7,
        genre: ["Sci-Fi", "Adventure"],
        poster: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival as Earth becomes increasingly uninhabitable.",
        director: "Christopher Nolan",
        duration: "2h 49m",
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
        releaseDate: "November 7, 2014",
    },
    {
        id: 2,
        title: "The Dark Knight",
        year: 2008,
        rating: 9.0,
        genre: ["Action", "Crime"],
        poster: "linear-gradient(135deg, #0f0f0f 0%, #1a1a1a 50%, #2d2d2d 100%)",
        description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        director: "Christopher Nolan",
        duration: "2h 32m",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Maggie Gyllenhaal"],
        releaseDate: "July 18, 2008",
    },
    {
        id: 3,
        title: "Inception",
        year: 2010,
        rating: 8.8,
        genre: ["Sci-Fi", "Thriller"],
        poster: "linear-gradient(135deg, #1e3a5f 0%, #2d5a87 50%, #3d7ab8 100%)",
        description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        director: "Christopher Nolan",
        duration: "2h 28m",
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page", "Tom Hardy"],
        releaseDate: "July 16, 2010",
    },
    {
        id: 4,
        title: "Pulp Fiction",
        year: 1994,
        rating: 8.9,
        genre: ["Crime", "Drama"],
        poster: "linear-gradient(135deg, #8b0000 0%, #a52a2a 50%, #cd5c5c 100%)",
        description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        director: "Quentin Tarantino",
        duration: "2h 34m",
        cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
        releaseDate: "October 14, 1994",
    },
    {
        id: 5,
        title: "The Matrix",
        year: 1999,
        rating: 8.7,
        genre: ["Sci-Fi", "Action"],
        poster: "linear-gradient(135deg, #003300 0%, #004d00 50%, #006600 100%)",
        description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
        director: "The Wachowskis",
        duration: "2h 16m",
        cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
        releaseDate: "March 31, 1999",
    },
    {
        id: 6,
        title: "Forrest Gump",
        year: 1994,
        rating: 8.8,
        genre: ["Drama", "Romance"],
        poster: "linear-gradient(135deg, #4a5568 0%, #718096 50%, #a0aec0 100%)",
        description: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
        director: "Robert Zemeckis",
        duration: "2h 22m",
        cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
        releaseDate: "July 6, 1994",
    },
    {
        id: 7,
        title: "The Shawshank Redemption",
        year: 1994,
        rating: 9.3,
        genre: ["Drama"],
        poster: "linear-gradient(135deg, #2c3e50 0%, #34495e 50%, #5d6d7e 100%)",
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        director: "Frank Darabont",
        duration: "2h 22m",
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
        releaseDate: "September 23, 1994",
    },
    {
        id: 8,
        title: "Fight Club",
        year: 1999,
        rating: 8.8,
        genre: ["Drama", "Thriller"],
        poster: "linear-gradient(135deg, #4a1c40 0%, #6b2c50 50%, #8b3c60 100%)",
        description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much, much more.",
        director: "David Fincher",
        duration: "2h 19m",
        cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"],
        releaseDate: "October 15, 1999",
    },
    {
        id: 9,
        title: "Gladiator",
        year: 2000,
        rating: 8.5,
        genre: ["Action", "Drama"],
        poster: "linear-gradient(135deg, #8b4513 0%, #a0522d 50%, #cd853f 100%)",
        description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        director: "Ridley Scott",
        duration: "2h 35m",
        cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"],
        releaseDate: "May 5, 2000",
    },
    {
        id: 10,
        title: "Avatar",
        year: 2009,
        rating: 7.9,
        genre: ["Sci-Fi", "Adventure"],
        poster: "linear-gradient(135deg, #006994 0%, #0099cc 50%, #00bfff 100%)",
        description: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
        director: "James Cameron",
        duration: "2h 42m",
        cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Stephen Lang"],
        releaseDate: "December 18, 2009",
    },
    {
        id: 11,
        title: "The Godfather",
        year: 1972,
        rating: 9.2,
        genre: ["Crime", "Drama"],
        poster: "linear-gradient(135deg, #1c1c1c 0%, #2d2d2d 50%, #3d3d3d 100%)",
        description: "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
        director: "Francis Ford Coppola",
        duration: "2h 55m",
        cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall"],
        releaseDate: "March 24, 1972",
    },
    {
        id: 12,
        title: "Parasite",
        year: 2019,
        rating: 8.5,
        genre: ["Thriller", "Drama"],
        poster: "linear-gradient(135deg, #2f4f4f 0%, #3d6b6b 50%, #4a8787 100%)",
        description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        director: "Bong Joon-ho",
        duration: "2h 12m",
        cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
        releaseDate: "May 30, 2019",
    },
];

// Sample reviews data
export const REVIEWS = {
    1: [
        { id: 1, user: "John Doe", avatar: "JD", rating: 5, comment: "A masterpiece of science fiction! The visuals are breathtaking and the emotional depth is incredible.", date: "2024-12-01" },
        { id: 2, user: "Sarah Miller", avatar: "SM", rating: 4, comment: "Christopher Nolan outdid himself. Some scenes had me in tears.", date: "2024-11-28" },
        { id: 3, user: "Mike Chen", avatar: "MC", rating: 5, comment: "One of those movies that stays with you long after the credits roll.", date: "2024-11-15" },
    ],
    2: [
        { id: 1, user: "Alex Turner", avatar: "AT", rating: 5, comment: "Heath Ledger's Joker is simply legendary. Best superhero movie ever made.", date: "2024-12-05" },
        { id: 2, user: "Emily Rose", avatar: "ER", rating: 5, comment: "The Dark Knight transcends the superhero genre. It's a crime thriller masterpiece.", date: "2024-11-20" },
    ],
    3: [
        { id: 1, user: "David Park", avatar: "DP", rating: 5, comment: "Mind-bending in the best way possible. You'll want to watch it multiple times.", date: "2024-12-03" },
        { id: 2, user: "Lisa Wang", avatar: "LW", rating: 4, comment: "Inception challenges your perception of reality. Absolutely brilliant!", date: "2024-11-25" },
    ],
    4: [
        { id: 1, user: "Chris Johnson", avatar: "CJ", rating: 5, comment: "Tarantino's dialogue is unmatched. Every scene is iconic.", date: "2024-12-02" },
    ],
    5: [
        { id: 1, user: "Rachel Green", avatar: "RG", rating: 5, comment: "Revolutionary when it came out and still holds up today. A true classic.", date: "2024-11-30" },
    ],
    6: [
        { id: 1, user: "Tom Baker", avatar: "TB", rating: 5, comment: "Life is like a box of chocolates. This movie is pure gold.", date: "2024-11-18" },
    ],
    7: [
        { id: 1, user: "Amanda Hill", avatar: "AH", rating: 5, comment: "The greatest movie ever made. Period. Morgan Freeman is incredible.", date: "2024-12-06" },
        { id: 2, user: "James Wilson", avatar: "JW", rating: 5, comment: "Hope is a good thing, and this movie proves it beautifully.", date: "2024-11-22" },
    ],
    8: [
        { id: 1, user: "Olivia Scott", avatar: "OS", rating: 4, comment: "The twist at the end blew my mind. Fincher is a genius.", date: "2024-11-28" },
    ],
    9: [
        { id: 1, user: "Robert Black", avatar: "RB", rating: 4, comment: "Russell Crowe delivers a powerful performance. Epic in every sense.", date: "2024-11-15" },
    ],
    10: [
        { id: 1, user: "Nina Patel", avatar: "NP", rating: 4, comment: "Visually stunning world-building. Pandora feels so real.", date: "2024-12-01" },
    ],
    11: [
        { id: 1, user: "Frank Romano", avatar: "FR", rating: 5, comment: "An offer you can't refuse to watch. Marlon Brando is iconic.", date: "2024-11-20" },
    ],
    12: [
        { id: 1, user: "Grace Kim", avatar: "GK", rating: 5, comment: "Deserved every Oscar it won. A masterful commentary on class.", date: "2024-12-04" },
    ],
};

export const GENRES = ["All", "Sci-Fi", "Action", "Drama", "Crime", "Thriller", "Adventure", "Romance"];
export const YEARS = ["All", "2019+", "2010-2018", "2000-2009", "1990-1999", "Pre-1990"];
export const SORT_OPTIONS = ["Rating", "Year", "Title"];
